parameters:
#    moraspirit_user.example.class: Moraspirit\UserBundle\Example

services:
#    moraspirit_user.example:
#        class: %moraspirit_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
