sudo: required
language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"

services:
  - docker

install:
  - docker build -t volma .
  - docker run -d -p 127.0.0.1:8081:8081 --name volma volma

before_script:
  - npm install mocha

script:
  - docker ps | grep -q volma
