parameters:
#    moraspirit_comment.example.class: Moraspirit\CommentBundle\Example

services:
#    moraspirit_comment.example:
#        class: %moraspirit_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
