parameters:
#    moraspirit_project.example.class: Moraspirit\ProjectBundle\Example

services:
#    moraspirit_project.example:
#        class: %moraspirit_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
