parameters:
#    moraspirit_task.example.class: Moraspirit\TaskBundle\Example

services:
#    moraspirit_task.example:
#        class: %moraspirit_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
