parameters:
#    moraspirit_site.example.class: Moraspirit\SiteBundle\Example

services:
#    moraspirit_site.example:
#        class: %moraspirit_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
